export const FILMS: string[] = [
  'Matrix',
  'The Lord of the Rings',
  'The Man Called Flintstone',
  'Casper the Friendly Ghost',
  'Peppa Pig',
  'Groundhog Day',
  'The Lake House',
  'The Terminal',
  'Miracle on 34th Street',
  'Harry Potter and the Sorcerer’s Stone',
  'Harry Potter and the Chamber of Secrets',
  'Pulp Fiction',
  'lord',
  'man',
  'football',
  'terminal',
  'pig',
  'peppa',
  'lake',
  'sea',
  'day',
  'family',
  'army',
  'night',
  'Terminator'
];
